# permissions for end users to edit webappcrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: webappcr-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: webappcr
    app.kubernetes.io/part-of: webappcr
    app.kubernetes.io/managed-by: kustomize
  name: webappcr-editor-role
rules:
- apiGroups:
  - crwebapp.my.domain
  resources:
  - webappcrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crwebapp.my.domain
  resources:
  - webappcrs/status
  verbs:
  - get
